### PR TITLE
script to add notes

### PR DESCRIPTION
**Pull request by rhasnainanwar**

### CODE REVIEW

**Comment by rhasnainanwar** [comment]
Make executable and add to path automatically when installed. You may need to edit the MakeFile.

**Comment by nil-two** [comment]
Thank you for using my exetension!

I saw the script you wrote.

GNOME extension basically supposed to be installed from [the official website](https://extensions.gnome.org/).
And, it cannot run any scripts during installation.
So, I think it won't be used by users if it placed here.

The Makefile is a thing put together some commands at development.
It doesn't assume to be used directly by users.

How about creating a repository separately?
I will add a link to it to README and the official website if you created.
The commit log doesn't confused and It is easy to refurbishment so I think it is a good way.

**Comment by rhasnainanwar** [comment]
That's a good idea.
Add a link to my forked copy of the extension.

**Comment by nil-two** [comment]
OK.
I just added a link to your fork to README.
https://github.com/kusabashira/short-memo/commit/e1cc854cf697f1870fe54defe72f45038bbcac56

**Pull request closed without merging**
